version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
       - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghostuser
      MYSQL_PASSWORD: ocrpassword

  ghost:
    depends_on:
      - mysql
    build: .
    restart: always
    ports:
      - "2368:2368"
    environment:
      NODE_ENV: production

volumes:
  db_data: {}
